In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/fenago/tf/main/Chapter4-Regression_and_Classification_Models/dataset/Summary_of_Weather.csv"


df = pd.read_csv(url)

In [ ]:
df.head()

,STA,Date,MaxTemp,MinTemp,MeanTemp,Snowfall,YR,MO,DA,MAX,MIN,MEA
0,10001,01-07-1942,25.555556,22.222222,23.888889,0.0,42,7,1,78.0,72.0,75.0
1,10001,02-07-1942,28.888889,21.666667,25.555556,0.0,42,7,2,84.0,71.0,78.0
2,10001,03-07-1942,26.111111,22.222222,24.444444,0.0,42,7,3,79.0,72.0,76.0
3,10001,04-07-1942,26.666667,22.222222,24.444444,0.0,42,7,4,80.0,72.0,76.0
4,10001,05-07-1942,26.666667,21.666667,24.444444,0.0,42,7,5,80.0,71.0,76.0

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y', errors='coerce')

In [ ]:
year_dummies = pd.get_dummies(df['Date'].dt.year, \
                                  prefix='year')
year_dummies

        year_1940  year_1941  year_1942  year_1943  year_1944  year_1945
0           False      False       True      False      False      False
1           False      False       True      False      False      False
2           False      False       True      False      False      False
3           False      False       True      False      False      False
4           False      False       True      False      False      False
...           ...        ...        ...        ...        ...        ...
119035      False      False      False      False      False       True
119036      False      False      False      False      False       True
119037      False      False      False      False      False       True
119038      False      False      False      False      False       True
119039      False      False      False      False      False       True

[119040 rows x 6 columns]

In [ ]:
month_dummies = pd.get_dummies(df['Date'].dt.month, \
                                   prefix='month')
month_dummies

,month_1,month_2,month_3,month_4,month_5,month_6,month_7,month_8,month_9,month_10,month_11,month_12
0,False,False,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
119035,False,False,False,False,False,False,False,False,False,False,False,True
119036,False,False,False,False,False,False,False,False,False,False,False,True
119037,False,False,False,False,False,False,False,False,False,False,False,True
119038,False,False,False,False,False,False,False,False,False,False,False,True
119039,False,False,False,False,False,False,False,False,False,False,False,True

In [ ]:
df = pd.concat([df, month_dummies, year_dummies], \
                   axis=1)

In [ ]:
# Check the existing columns in your DataFrame
print(df.columns)

# Drop only the columns that exist in the DataFrame
columns_to_drop = ['Date', 'Precip','Snowfall', 'PoorWeather', 'PRCP',
        'TSHDSBRSGF', 'SNF']
existing_columns = [col for col in columns_to_drop if col in df.columns]

df.drop(existing_columns, axis=1, inplace=True)

Index(['STA', 'Date', 'MaxTemp', 'MinTemp', 'MeanTemp', 'Snowfall', 'YR', 'MO',
       'DA', 'MAX', 'MIN', 'MEA', 'month_1', 'month_2', 'month_3', 'month_4',
       'month_5', 'month_6', 'month_7', 'month_8', 'month_9', 'month_10',
       'month_11', 'month_12', 'year_1940', 'year_1941', 'year_1942',
       'year_1943', 'year_1944', 'year_1945'],
      dtype='object')

In [ ]:
df.dtypes

STA            int64
MaxTemp      float64
MinTemp      float64
MeanTemp     float64
YR             int64
MO             int64
DA             int64
MAX          float64
MIN          float64
MEA          float64
month_1         bool
month_2         bool
month_3         bool
month_4         bool
month_5         bool
month_6         bool
month_7         bool
month_8         bool
month_9         bool
month_10        bool
month_11        bool
month_12        bool
year_1940       bool
year_1941       bool
year_1942       bool
year_1943       bool
year_1944       bool
year_1945       bool
month_1         bool
month_2         bool
month_3         bool
month_4         bool
month_5         bool
month_6         bool
month_7         bool
month_8         bool
month_9         bool
month_10        bool
month_11        bool
month_12        bool
year_1940       bool
year_1941       bool
year_1942       bool
year_1943       bool
year_1944       bool
year_1945       bool
dtype: object